/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul10;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        rdlaki = new javax.swing.JRadioButton();
        rdperemuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vrinda", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 780, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic School");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 320, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 80);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISIKAN DATA SISWA :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 140, 14);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(2, 2, 270, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NIS :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 50, 100, 14);
        jPanel2.add(txtNIS);
        txtNIS.setBounds(10, 70, 250, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 50, 14);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNama);
        txtNama.setBounds(10, 120, 250, 20);

        rdlaki.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdlaki);
        rdlaki.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdlaki.setText("Laki - Laki");
        jPanel2.add(rdlaki);
        rdlaki.setBounds(10, 140, 83, 23);

        rdperemuan.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdperemuan);
        rdperemuan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdperemuan.setText("Perempuan");
        jPanel2.add(rdperemuan);
        rdperemuan.setBounds(110, 140, 93, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kelas :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 170, 50, 14);
        jPanel2.add(txtKelas);
        txtKelas.setBounds(10, 190, 250, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Email :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 220, 60, 14);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(10, 240, 250, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Alamat :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 270, 70, 14);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 250, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 270, 400);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setForeground(new java.awt.Color(255, 0, 0));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel4.add(save);
        save.setBounds(10, 10, 70, 23);

        delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel4.add(delete);
        delete.setBounds(100, 10, 70, 23);

        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear);
        clear.setBounds(190, 10, 70, 23);

        refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 0, 0));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel4.add(refresh);
        refresh.setBounds(280, 10, 80, 23);

        edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 0, 0));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel4.add(edit);
        edit.setBounds(380, 10, 70, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 90, 540, 40);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama_Siswa", "Jenis_Kelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 520, 340);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(290, 130, 540, 360);

        setBounds(0, 0, 857, 534);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    if ("".equals(txtNIS.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtKelas.getText()) || "".equals(txtNama.getText()) ||
            "".equals(txtEmail.getText())){
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
    } else {
        String JK = "";
            if(rdlaki.isSelected()){
                JK = "L";
            }else{
                JK = "P";
            }
    
    String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat) "
            + "VALUES('"+txtNIS.getText()+"','"+txtNama.getText()+"','"+JK+"','"
            +txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
    int status = KoneksiDB.execute(SQL);
    if (status == 1){
        JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan", "Berhasil!!", JOptionPane.INFORMATION_MESSAGE);
        selectData();
    }else{
        JOptionPane.showMessageDialog(this, "Data gagal dimasukkan", "Coba Lagi Ya! :*", JOptionPane.WARNING_MESSAGE);
        }
      }
    }//GEN-LAST:event_saveActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
    selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
    int baris = tb1.getSelectedRow();
        if (baris != -1){
            String NIS = tb1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Berhasil, We Did It", JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Coba Lagi Ya :*", JOptionPane.WARNING_MESSAGE);
            }
        }else{
             JOptionPane.showMessageDialog(this, "Pilih Baris Data Dulu Ya -__-", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    txtNama.setText("");
    txtKelas.setText("");
    txtNIS.setText("");
    buttonGroup1.clearSelection();
    txtEmail.setText("");
    txtAlamat.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    if ("".equals(txtNIS.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtKelas.getText()) || "".equals(txtNama.getText()) ||
            "".equals(txtEmail.getText())){
        JOptionPane.showMessageDialog(this, "Harap Lengkapi data!!", "Error", JOptionPane.WARNING_MESSAGE);
    }else{
        String JK = "";
            if (rdlaki.isSelected()){
            JK = "L";
        }else{
        JK = "P";        
        }
      String SQL = "UPDATE t_siswa SET NIS='"+txtNIS.getText()+"',NamaSiswa='"+txtNama.getText()+"',JenisKelamin='"+JK+"',Kelas='"+txtKelas.getText()+
              "',Email='"+txtEmail.getText()+"',Alamat='"+txtNIS.getText()+"' WHERE NIS='"+txtNIS.getText()+"'";
             
      int status = KoneksiDB.execute(SQL);
      if (status == 1){
          JOptionPane.showMessageDialog(this, "Data Berhasil di update", "Sukses", JOptionPane.INFORMATION_MESSAGE);
          selectData();
      }else{
          JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
      }
              
    }       
    }//GEN-LAST:event_editActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
    int baris = tb1.getSelectedRow();
    if (baris != -1){
        txtNIS.setText(tb1.getValueAt(baris, 0).toString());
        txtNama.setText(tb1.getValueAt(baris, 1).toString());
        if ("Laki-Laki".equals(tb1.getValueAt(baris, 2).toString())){
            rdlaki.setSelected(true);
        }else{
            rdperemuan.setSelected(true);
        }
        txtKelas.setText(tb1.getValueAt(baris, 3).toString());
        txtEmail.setText(tb1.getValueAt(baris, 4).toString());
        txtAlamat.setText(tb1.getValueAt(baris, 5).toString());
    }
    }//GEN-LAST:event_tb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdlaki;
    private javax.swing.JRadioButton rdperemuan;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tb1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom); 
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
              String NIS = rs.getString(1);
              String NamaSiswa = rs.getString(2);
              String JenisKelamin = "";
                if ("L".equals(rs.getString(3))){
                    JenisKelamin = "Laki-Laki";
                }else{
                    JenisKelamin = "Perempuan";
                }
              String Kelas = rs.getString(4);
              String Email = rs.getString(5);
              String Alamat = rs.getString(6);
              String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
              dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb1.setModel(dtm);
    }

}
